version: '2'
services:
  clickhouse:
    image: docker.io/clickhouse/clickhouse-server:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '8123:8123'
      - '9000:9000'
    volumes:
      - clickhouse_data:/var/lib/clickhouse/
volumes:
  clickhouse_data:
    driver: local


    # docker exec -it some-clickhouse-server clickhouse-client
    # CREATE DATABASE IF NOT EXISTS stock_zh_a_hist